#!/bin/bash
mainremote=$(git remote get-url origin > /dev/null 2>&1 && echo 'origin')

gitpr() {
    origin_url=$(git ls-remote --get-url $(git mainremote))
    fork_owner=$(git ls-remote --get-url phil | sed 's|git@github.*:\(.*\)/.*|\1|')
    fork_url=$(git ls-remote --get-url phil);
    trunk=$(git remote show phil | sed -n '/HEAD branch/s/.*: //p')

    compare_url_base=$(echo $origin_url | sed 's/git@\(.*\):\(.*\)$/https:\/\/\1\/\2/' | sed 's|\.git$||')
    compare_path="/compare/$trunk...$fork_owner:$(git symbolic-ref HEAD | sed 's|refs/heads/||')?expand=1"
    open $compare_url_base$compare_path
}

# hub = "!f() { \
#     open \"$(git ls-remote --get-url $(git mainremote) \
#       | sed 's|git@github.com:\\(.*\\)$|https://github.com/\\1|' \
#       | sed 's|git@'$(git enterprisehost)':\\(.*\\)$|https://'$(git enterprisehost)'/\\1|' \
#       | sed 's|\\.git$||'; \
#       )\"; \
#   }; f"
