#!/bin/bash
main_remote() {
    echo $(git remote get-url origin > /dev/null 2>&1 && echo 'origin')
}

origin_url() {
    url=$(git ls-remote --get-url $(main_remote))
    echo $(echo $url | sed 's|git@\(.*\):\(.*\)$|https://\1/\2|' | sed 's|\.git$||')
}

gitpr() {
    fork_owner=$(git ls-remote --get-url phil | sed 's|git@github.*:\(.*\)/.*|\1|')
    fork_url=$(git ls-remote --get-url phil);
    trunk=$(git remote show phil | sed -n '/HEAD branch/s/.*: //p')

    compare_path="/compare/$trunk...$fork_owner:$(git symbolic-ref HEAD | sed 's|refs/heads/||')?expand=1"
    open $(origin_url)$compare_path
}

gitrepo() { \
    open $(origin_url)
}
